<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('article', 'lead', 'string', '4096', array(
             ));
        $this->addColumn('article', 'contents', 'string', '4096', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('article', 'lead');
        $this->removeColumn('article', 'contents');
    }
}